server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lc_tcc?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml
